/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.95
 * Generated at: 2024-10-13 12:40:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Online Laundry Management System</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css\">\r\n");
      out.write("    <style>\r\n");
      out.write("        /* Define CSS Variables */\r\n");
      out.write("        :root {\r\n");
      out.write("            --menu-bg-color: #333; /* Dark background for navigation */\r\n");
      out.write("            --menu-text-color: white; /* Text color for menu */\r\n");
      out.write("            --menu-hover-bg-color: #444; /* Hover background color */\r\n");
      out.write("            --primary-color: #ff6f61; /* Primary button color */\r\n");
      out.write("            --accent-color: white; /* Accent color for text */\r\n");
      out.write("            --search-bar-bg: #555; /* Background for search bar */\r\n");
      out.write("            --hover-color: #e65c50; /* Hover color for buttons */\r\n");
      out.write("            --body-bg-color: #f8f9fa; /* Light background for the body */\r\n");
      out.write("            --info-card-bg: white; /* Background for info cards */\r\n");
      out.write("            --info-card-hover-bg: #f0f0f0; /* Hover background for info cards */\r\n");
      out.write("            --footer-bg-color: #333; /* Footer background color */\r\n");
      out.write("            --footer-text-color: white; /* Footer text color */\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Global Styles */\r\n");
      out.write("        body {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            font-family: Arial, sans-serif;\r\n");
      out.write("            background-color: var(--body-bg-color);\r\n");
      out.write("            color: #333;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Header and Navigation Bar Styles */\r\n");
      out.write("        header {\r\n");
      out.write("            background-color: var(--menu-bg-color);\r\n");
      out.write("            padding: 18px 0;\r\n");
      out.write("            box-shadow: 0 4px 10px rgba(0, 0, 0, 0.2);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        nav {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            position: relative;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        nav ul {\r\n");
      out.write("            list-style-type: none;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        nav ul li {\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            margin: 0 20px;\r\n");
      out.write("            position: relative;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        nav ul li a {\r\n");
      out.write("            color: var(--menu-text-color); /* White text on darker background */\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("            padding: 12px 20px;\r\n");
      out.write("            transition: background-color 0.3s ease, transform 0.2s ease;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        nav ul li a:hover {\r\n");
      out.write("            background-color: var(--menu-hover-bg-color); /* Slightly lighter gray */\r\n");
      out.write("            transform: scale(1.05);\r\n");
      out.write("            box-shadow: 0 4px 10px rgba(0, 0, 0, 0.2);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        nav ul li a::after {\r\n");
      out.write("            content: '';\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            width: 0;\r\n");
      out.write("            height: 3px;\r\n");
      out.write("            background-color: var(--primary-color); /* Coral underline on hover */\r\n");
      out.write("            left: 0;\r\n");
      out.write("            bottom: 0;\r\n");
      out.write("            transition: width 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        nav ul li a:hover::after {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Search Bar Styles */\r\n");
      out.write("        .search-container {\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            vertical-align: middle;\r\n");
      out.write("            margin-left: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .search-container input {\r\n");
      out.write("            padding: 8px;\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 20px;\r\n");
      out.write("            width: 230px;\r\n");
      out.write("            background-color: var(--search-bar-bg); /* Medium dark background for search */\r\n");
      out.write("            color: var(--accent-color); /* White text in search bar */\r\n");
      out.write("            outline: none;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .search-container input:focus {\r\n");
      out.write("            width: 270px;\r\n");
      out.write("            background-color: #666;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .search-container button {\r\n");
      out.write("            padding: 8px 12px;\r\n");
      out.write("            background-color: var(--primary-color);\r\n");
      out.write("            color: var(--accent-color);\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 20px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            margin-left: 5px;\r\n");
      out.write("            transition: background-color 0.3s ease, box-shadow 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .search-container button:hover {\r\n");
      out.write("            background-color: var(--hover-color);\r\n");
      out.write("            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.2);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Home Section Styles */\r\n");
      out.write("        .home-section {\r\n");
      out.write("            position: relative;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("            height: 60vh; /* Adjusted height for better visibility */\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .slider {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            position: relative;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .slider-img {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            object-fit: cover; /* Maintain aspect ratio */\r\n");
      out.write("            transition: opacity 0.5s;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .welcome-text-container {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 50%;\r\n");
      out.write("            left: 50%;\r\n");
      out.write("            transform: translate(-50%, -50%);\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            color: white;\r\n");
      out.write("            background: rgba(0, 0, 0, 0.4);\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .welcome-text h1 {\r\n");
      out.write("            font-size: 2.5em;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            text-shadow: 2px 2px 5px rgba(0, 0, 0, 0.7);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .welcome-text p {\r\n");
      out.write("            font-size: 1.2em;\r\n");
      out.write("            margin: 10px 0;\r\n");
      out.write("            text-shadow: 1px 1px 3px rgba(0, 0, 0, 0.5);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .welcome-text button {\r\n");
      out.write("            background-color: var(--primary-color); /* Stylish button color */\r\n");
      out.write("            color: white;\r\n");
      out.write("            border: none;\r\n");
      out.write("            padding: 10px 20px;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            font-size: 1em;\r\n");
      out.write("            transition: background-color 0.3s;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .welcome-text button:hover {\r\n");
      out.write("            background-color: #e65c50; /* Darker shade on hover */\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Info Section Styles */\r\n");
      out.write("        .info-section {\r\n");
      out.write("            padding: 40px 20px;\r\n");
      out.write("            background-color: #f8f9fa;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            flex-wrap: wrap;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .info-cards {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: space-around;\r\n");
      out.write("            flex-wrap: wrap;\r\n");
      out.write("            max-width: 1200px;\r\n");
      out.write("            margin: auto;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .info-card {\r\n");
      out.write("            background-color: var(--info-card-bg); /* Card background */\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            margin: 10px;\r\n");
      out.write("            flex: 1 1 200px; /* Responsive card size */\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            transition: transform 0.3s, background-color 0.3s;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .info-card:hover {\r\n");
      out.write("            transform: scale(1.05); /* Slight zoom effect on hover */\r\n");
      out.write("            background-color: var(--info-card-hover-bg);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .info-card i {\r\n");
      out.write("            font-size: 2em;\r\n");
      out.write("            color: var(--primary-color); /* Icon color */\r\n");
      out.write("            margin-bottom: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .info-card h3 {\r\n");
      out.write("            margin: 10px 0;\r\n");
      out.write("            color: #333;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .info-card p {\r\n");
      out.write("            color: #666;\r\n");
      out.write("            font-size: 1em;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Footer Styles */\r\n");
      out.write("        footer.social-media {\r\n");
      out.write("            background-color: var(--footer-bg-color); /* Keep footer color unchanged */\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            color: var(--footer-text-color);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        footer .social-container {\r\n");
      out.write("            margin-bottom: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        footer .social-icon {\r\n");
      out.write("            color: white; /* Icon color */\r\n");
      out.write("            margin: 0 10px;\r\n");
      out.write("            font-size: 1.5em;\r\n");
      out.write("            transition: color 0.3s;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        footer .social-icon:hover {\r\n");
      out.write("            color: var(--primary-color); /* Change icon color on hover */\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        footer p {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            font-size: 0.9em;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Responsive Styles */\r\n");
      out.write("        @media (max-width: 768px) {\r\n");
      out.write("            nav ul {\r\n");
      out.write("                flex-direction: column;\r\n");
      out.write("                gap: 10px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .search-container {\r\n");
      out.write("                margin-left: 0;\r\n");
      out.write("                margin-top: 10px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .info-cards {\r\n");
      out.write("                flex-direction: column;\r\n");
      out.write("                align-items: center;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .info-card {\r\n");
      out.write("                width: 80%;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .pricing-table {\r\n");
      out.write("                flex: 0 0 100%; /* Stack pricing tables on smaller screens */\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .welcome-text-container {\r\n");
      out.write("                padding: 10px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .welcome-text h1 {\r\n");
      out.write("                font-size: 2em;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .welcome-text p {\r\n");
      out.write("                font-size: 1em;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .info-section {\r\n");
      out.write("                padding: 20px 10px;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <header>\r\n");
      out.write("        <nav>\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><a href=\"#\">Home</a></li>\r\n");
      out.write("                <li><a href=\"services.jsp\">Services</a></li>\r\n");
      out.write("                <li><a href=\"orderinsert.jsp\">Order Pickup</a></li>\r\n");
      out.write("                <li><a href=\"OrderTrackingPage.jsp\">Track Orders</a></li>\r\n");
      out.write("                <li><a href=\"pricing.jsp\">Pricing</a></li>\r\n");
      out.write("                <li><a href=\"contact.jsp\">Contact Us</a></li>\r\n");
      out.write("                <li><a href=\"Login.jsp\">Login</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <div class=\"search-container\">\r\n");
      out.write("                <input type=\"text\" id=\"search\" placeholder=\"Search...\">\r\n");
      out.write("                <button onclick=\"performSearch()\">Search</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </nav>\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("    <!-- Home Section with Slider -->\r\n");
      out.write("    <section class=\"home-section\">\r\n");
      out.write("        <div class=\"slider\">\r\n");
      out.write("            <img src=\"CSS/image1.jpg\" alt=\"Laundry Service\" class=\"slider-img\" id=\"slider-img\">\r\n");
      out.write("            <div class=\"welcome-text-container\">\r\n");
      out.write("                <div class=\"welcome-text\">\r\n");
      out.write("                    <h1>Welcome to <span class=\"highlight\">Your Ultimate Laundry Partner</span></h1>\r\n");
      out.write("                    <p>Effortless laundry solutions with a touch of convenience and care.</p>\r\n");
      out.write("                    <button onclick=\"window.location.href='services.jsp'\">Discover Our Services</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <!-- New Information Section -->\r\n");
      out.write("    <section class=\"info-section\">\r\n");
      out.write("        <div class=\"info-cards\">\r\n");
      out.write("            <div class=\"info-card\">\r\n");
      out.write("                <i class=\"fas fa-truck\"></i>\r\n");
      out.write("                <h3>Fast Pickup & Delivery</h3>\r\n");
      out.write("                <p>Experience swift and reliable pickup and delivery right at your doorstep.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"info-card\">\r\n");
      out.write("                <i class=\"fas fa-leaf\"></i>\r\n");
      out.write("                <h3>Eco-Friendly</h3>\r\n");
      out.write("                <p>We use sustainable and eco-friendly detergents for a greener planet.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"info-card\">\r\n");
      out.write("                <i class=\"fas fa-dollar-sign\"></i>\r\n");
      out.write("                <h3>Affordable Pricing</h3>\r\n");
      out.write("                <p>Quality laundry service without breaking the bank.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"info-card\">\r\n");
      out.write("                <i class=\"fas fa-cogs\"></i>\r\n");
      out.write("                <h3>Customizable Services</h3>\r\n");
      out.write("                <p>Tailor-made solutions to fit your specific laundry needs.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <!-- Social Media Footer -->\r\n");
      out.write("    <footer class=\"social-media\">\r\n");
      out.write("        <div class=\"social-container\">\r\n");
      out.write("            <a href=\"https://www.facebook.com\" target=\"_blank\" class=\"social-icon\">\r\n");
      out.write("                <i class=\"fab fa-facebook-f\"></i>\r\n");
      out.write("            </a>\r\n");
      out.write("            <a href=\"https://www.youtube.com\" target=\"_blank\" class=\"social-icon\">\r\n");
      out.write("                <i class=\"fab fa-youtube\"></i>\r\n");
      out.write("            </a>\r\n");
      out.write("            <a href=\"https://www.instagram.com\" target=\"_blank\" class=\"social-icon\">\r\n");
      out.write("                <i class=\"fab fa-instagram\"></i>\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <p>&copy; 2024 Online Laundry Management System. All rights reserved.</p>\r\n");
      out.write("    </footer>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        function performSearch() {\r\n");
      out.write("            var query = document.getElementById(\"search\").value;\r\n");
      out.write("            if (query) {\r\n");
      out.write("                alert(\"Searching for: \" + query);\r\n");
      out.write("                // Implement actual search functionality here\r\n");
      out.write("            } else {\r\n");
      out.write("                alert(\"Please enter a search term.\");\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        const images = ['CSS/image1.jpg', 'CSS/image2.jpg', 'CSS/image3.jpg']; \r\n");
      out.write("        let currentIndex = 0;\r\n");
      out.write("\r\n");
      out.write("        function changeImage() {\r\n");
      out.write("            const sliderImg = document.getElementById('slider-img');\r\n");
      out.write("            currentIndex = (currentIndex + 1) % images.length; // Cycle through images\r\n");
      out.write("            sliderImg.src = images[currentIndex];\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        // Change image every 3 seconds\r\n");
      out.write("        setInterval(changeImage, 3000);\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
