/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.95
 * Generated at: 2024-10-13 12:42:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class OrderTrackingPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>Track Orders - Online Laundry Management System</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"track.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css\">\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("/* Define CSS Variables for easy customization */\r\n");
      out.write(":root {\r\n");
      out.write("	--primary-color: #ff6f61; /* Coral Pink */\r\n");
      out.write("	--secondary-color: #ff9a76; /* Light Coral */\r\n");
      out.write("	--accent-color: #ffffff; /* White */\r\n");
      out.write("	--hover-color: #ff4824; /* Darker Coral */\r\n");
      out.write("	--menu-bg-color: #333; /* Darker gray for menu bar */\r\n");
      out.write("	--menu-hover-bg-color: #444; /* Slightly lighter gray for hover */\r\n");
      out.write("	--menu-text-color: #ffffff; /* White text for contrast */\r\n");
      out.write("	--search-bar-bg: #555; /* Medium dark background for search bar */\r\n");
      out.write("	--bg-gradient-start: #f8f9fa; /* Light Gradient Start */\r\n");
      out.write("	--bg-gradient-end: #e0f7fa; /* Light Teal Gradient End */\r\n");
      out.write("	--text-primary: #212529; /* Darker text color */\r\n");
      out.write("	--button-hover-color: #ff4824; /* Deep Coral */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("* {\r\n");
      out.write("	margin: 0;\r\n");
      out.write("	padding: 0;\r\n");
      out.write("	box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("	font-family: 'Arial', sans-serif;\r\n");
      out.write("	background: linear-gradient(to right, var(--bg-gradient-start),\r\n");
      out.write("		var(--bg-gradient-end));\r\n");
      out.write("	color: var(--text-primary);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Darker Menu Bar */\r\n");
      out.write("header {\r\n");
      out.write("	background-color: var(--menu-bg-color);\r\n");
      out.write("	padding: 15px 0;\r\n");
      out.write("	box-shadow: 0 4px 10px rgba(0, 0, 0, 0.2);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("nav {\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	position: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("nav ul {\r\n");
      out.write("	list-style-type: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("nav ul li {\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("	margin: 0 20px;\r\n");
      out.write("	position: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("nav ul li a {\r\n");
      out.write("	color: var(--menu-text-color); /* White text on darker background */\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	font-size: 18px;\r\n");
      out.write("	padding: 12px 20px;\r\n");
      out.write("	transition: background-color 0.3s ease, transform 0.2s ease;\r\n");
      out.write("	position: relative;\r\n");
      out.write("	border-radius: 8px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("nav ul li a:hover {\r\n");
      out.write("	background-color: var(--menu-hover-bg-color);\r\n");
      out.write("	/* Slightly lighter gray */\r\n");
      out.write("	transform: scale(1.05);\r\n");
      out.write("	box-shadow: 0 4px 10px rgba(0, 0, 0, 0.2);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("nav ul li a::after {\r\n");
      out.write("	content: '';\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	width: 0;\r\n");
      out.write("	height: 3px;\r\n");
      out.write("	background-color: var(--primary-color); /* Coral underline on hover */\r\n");
      out.write("	left: 0;\r\n");
      out.write("	bottom: 0;\r\n");
      out.write("	transition: width 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("nav ul li a:hover::after {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Search Bar */\r\n");
      out.write(".search-container {\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("	vertical-align: middle;\r\n");
      out.write("	margin-left: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".search-container input {\r\n");
      out.write("	padding: 8px;\r\n");
      out.write("	font-size: 16px;\r\n");
      out.write("	border: none;\r\n");
      out.write("	border-radius: 20px;\r\n");
      out.write("	width: 230px;\r\n");
      out.write("	background-color: var(--search-bar-bg);\r\n");
      out.write("	/* Medium dark background for search */\r\n");
      out.write("	color: var(--accent-color); /* White text in search bar */\r\n");
      out.write("	outline: none;\r\n");
      out.write("	transition: all 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".search-container input:focus {\r\n");
      out.write("	width: 270px;\r\n");
      out.write("	background-color: #666;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".search-container button {\r\n");
      out.write("	padding: 8px 12px;\r\n");
      out.write("	background-color: var(--primary-color);\r\n");
      out.write("	color: var(--accent-color);\r\n");
      out.write("	border: none;\r\n");
      out.write("	border-radius: 20px;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("	margin-left: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".search-container button:hover {\r\n");
      out.write("	background-color: var(--hover-color);\r\n");
      out.write("	box-shadow: 0 4px 6px rgba(0, 0, 0, 0.2);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Home Section */\r\n");
      out.write(".home-section {\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	padding: 100px 20px;\r\n");
      out.write("	background-color: transparent; /* Let the gradient background show */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h1 {\r\n");
      out.write("	font-size: 42px;\r\n");
      out.write("	color: var(--primary-color);\r\n");
      out.write("	margin-bottom: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("p {\r\n");
      out.write("	font-size: 20px;\r\n");
      out.write("	color: var(--text-primary);\r\n");
      out.write("	margin-bottom: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("button {\r\n");
      out.write("	padding: 10px 20px;\r\n");
      out.write("	font-size: 18px;\r\n");
      out.write("	background-color: var(--primary-color);\r\n");
      out.write("	color: var(--accent-color);\r\n");
      out.write("	border: none;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("	border-radius: 20px;\r\n");
      out.write("	transition: background-color 0.3s ease, transform 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("button:hover {\r\n");
      out.write("	background-color: var(--button-hover-color);\r\n");
      out.write("	transform: scale(1.05);\r\n");
      out.write("}\r\n");
      out.write("/* Slider Styling */\r\n");
      out.write("\r\n");
      out.write(".social-media a {\r\n");
      out.write("	color: var(--accent-color);\r\n");
      out.write("	font-size: 24px;\r\n");
      out.write("	margin: 0 15px;\r\n");
      out.write("	transition: color 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".social-media a:hover {\r\n");
      out.write("	color: var(--primary-color);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".social-icon img {\r\n");
      out.write("	width: 24px;\r\n");
      out.write("	height: 24px;\r\n");
      out.write("	transition: transform 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".social-icon img:hover {\r\n");
      out.write("	transform: scale(1.1);\r\n");
      out.write("}\r\n");
      out.write("/* General Reset */\r\n");
      out.write("* {\r\n");
      out.write("	margin: 0;\r\n");
      out.write("	padding: 0;\r\n");
      out.write("	box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Body Styling */\r\n");
      out.write("body {\r\n");
      out.write("	font-family: 'Arial', sans-serif;\r\n");
      out.write("	background-color: #f8f9fa; /* Light gray background */\r\n");
      out.write("	color: #333; /* Dark text */\r\n");
      out.write("	line-height: 1.6;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Header and Navigation Bar */\r\n");
      out.write("header {\r\n");
      out.write("	background-color: #333; /* Dark gray */\r\n");
      out.write("	padding: 15px 0;\r\n");
      out.write("	box-shadow: 0 4px 10px rgba(0, 0, 0, 0.2);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("nav ul {\r\n");
      out.write("	list-style: none;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("nav ul li {\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("	margin: 0 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("nav ul li a {\r\n");
      out.write("	color: #fff; /* White text */\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	padding: 10px 20px;\r\n");
      out.write("	font-size: 18px;\r\n");
      out.write("	transition: background-color 0.3s ease, transform 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("nav ul li a:hover {\r\n");
      out.write("	background-color: #444; /* Slightly lighter gray */\r\n");
      out.write("	transform: scale(1.05);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".search-container {\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("	margin-left: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".search-container input {\r\n");
      out.write("	padding: 8px;\r\n");
      out.write("	border-radius: 20px;\r\n");
      out.write("	border: none;\r\n");
      out.write("	outline: none;\r\n");
      out.write("	width: 220px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".search-container button {\r\n");
      out.write("	padding: 8px 15px;\r\n");
      out.write("	border-radius: 20px;\r\n");
      out.write("	background-color: #ff6f61; /* Coral */\r\n");
      out.write("	color: #fff;\r\n");
      out.write("	border: none;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("	transition: background-color 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".search-container button:hover {\r\n");
      out.write("	background-color: #ff4824; /* Darker Coral */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Social Media Footer */\r\n");
      out.write("footer {\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	padding: 20px;\r\n");
      out.write("	background-color: #333;\r\n");
      out.write("	color: #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("footer a {\r\n");
      out.write("	color: #fff;\r\n");
      out.write("	margin: 0 15px;\r\n");
      out.write("	font-size: 24px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("footer a:hover {\r\n");
      out.write("	color: #ff6f61;\r\n");
      out.write("}\r\n");
      out.write("/* Track Orders Section */\r\n");
      out.write(".track-orders-section {\r\n");
      out.write("	max-width: 800px;\r\n");
      out.write("	margin: 50px auto;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	padding: 20px;\r\n");
      out.write("	background-color: #fff; /* White background */\r\n");
      out.write("	box-shadow: 0 4px 10px rgba(0, 0, 0, 0.1); /* Light shadow */\r\n");
      out.write("	border-radius: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".track-orders-section h1 {\r\n");
      out.write("	font-size: 36px;\r\n");
      out.write("	margin-bottom: 20px;\r\n");
      out.write("	color: var(--primary-color); /* Coral */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".track-orders-section p {\r\n");
      out.write("	font-size: 18px;\r\n");
      out.write("	margin-bottom: 30px;\r\n");
      out.write("	color: #666;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".tracking-form {\r\n");
      out.write("	max-width: 600px;\r\n");
      out.write("	margin: 0 auto;\r\n");
      out.write("	text-align: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-group {\r\n");
      out.write("	margin-bottom: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-group label {\r\n");
      out.write("	display: block;\r\n");
      out.write("	font-size: 16px;\r\n");
      out.write("	color: #333;\r\n");
      out.write("	margin-bottom: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-group input {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	padding: 10px;\r\n");
      out.write("	font-size: 16px;\r\n");
      out.write("	border: 1px solid #ddd;\r\n");
      out.write("	border-radius: 5px;\r\n");
      out.write("	outline: none;\r\n");
      out.write("	transition: border-color 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-group input:focus {\r\n");
      out.write("	border-color: var(--primary-color); /* Coral border on focus */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-group #error-message {\r\n");
      out.write("	font-size: 14px;\r\n");
      out.write("	color: red;\r\n");
      out.write("	margin-top: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Button Styling */\r\n");
      out.write("button[type=\"submit\"] {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	padding: 10px;\r\n");
      out.write("	font-size: 18px;\r\n");
      out.write("	background-color: var(--primary-color); /* Coral */\r\n");
      out.write("	color: #fff;\r\n");
      out.write("	border: none;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("	border-radius: 5px;\r\n");
      out.write("	transition: background-color 0.3s ease, transform 0.2s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("button[type=\"submit\"]:hover {\r\n");
      out.write("	background-color: #ff4824; /* Darker Coral */\r\n");
      out.write("	transform: scale(1.05);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Order Status */\r\n");
      out.write("#order-status {\r\n");
      out.write("	margin-top: 30px;\r\n");
      out.write("	padding: 15px;\r\n");
      out.write("	background-color: #f1f1f1;\r\n");
      out.write("	border: 1px solid #ddd;\r\n");
      out.write("	border-radius: 5px;\r\n");
      out.write("	display: none; /* Hidden initially */\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<header>\r\n");
      out.write("		<nav>\r\n");
      out.write("			<ul>\r\n");
      out.write("				<li><a href=\"home.jsp\">Home</a></li>\r\n");
      out.write("				<li><a href=\"services.jsp\">Services</a></li>\r\n");
      out.write("				<li><a href=\"orderinsert.jsp\">Order Pickup</a></li>\r\n");
      out.write("				<li><a href=\"#\">Track Orders</a></li>\r\n");
      out.write("				<li><a href=\"pricing.jsp\">Pricing</a></li>\r\n");
      out.write("				<li><a href=\"contact.jsp\">Contact Us</a></li>\r\n");
      out.write("				<li><a href=\"Login.jsp\">Login</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("			<div class=\"search-container\">\r\n");
      out.write("				<input type=\"text\" id=\"search\" placeholder=\"Search...\">\r\n");
      out.write("				<button onclick=\"performSearch()\">Search</button>\r\n");
      out.write("			</div>\r\n");
      out.write("		</nav>\r\n");
      out.write("	</header>\r\n");
      out.write("\r\n");
      out.write("	<!-- Track Orders Section -->\r\n");
      out.write("	<section class=\"track-orders-section\">\r\n");
      out.write("		<h1>Track Your Order</h1>\r\n");
      out.write("		<p>Enter your order number or customer details to track the status\r\n");
      out.write("			of your laundry order.</p>\r\n");
      out.write("\r\n");
      out.write("		<!-- Tracking Form -->\r\n");
      out.write("		\r\n");
      out.write("		<form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/OrderTrackServlet\" method=\"POST\" class=\"tracking-form\" onsubmit=\"return validateForm()\">\r\n");
      out.write("		\r\n");
      out.write("\r\n");
      out.write("			<div class=\"form-group\">\r\n");
      out.write("				<label for=\"order-number\">Order Number:</label> <input type=\"text\"\r\n");
      out.write("					id=\"order-number\" name=\"order_number\"\r\n");
      out.write("					placeholder=\"Enter your order number\" required> <span\r\n");
      out.write("					id=\"error-message\" style=\"color: red;\"> </span>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"form-group\">\r\n");
      out.write("				<label for=\"customer-email\">Customer Email (Optional):</label> <input\r\n");
      out.write("					type=\"email\" id=\"customer-email\" name=\"customer_email\"\r\n");
      out.write("					placeholder=\"Enter your email\">\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"form-group\">\r\n");
      out.write("				<label for=\"order-date\">Order Date (Optional):</label> <input\r\n");
      out.write("					type=\"date\" id=\"order-date\" name=\"order_date\">\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<button type=\"submit\">Track Order</button>\r\n");
      out.write("		</form>\r\n");
      out.write("\r\n");
      out.write("		<!-- Order Status Information -->\r\n");
      out.write("		<div class=\"order-status\" id=\"order-status\">\r\n");
      out.write("			<!-- This will be populated dynamically -->\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("\r\n");
      out.write("	<!-- Social Media Footer -->\r\n");
      out.write("	<footer class=\"social-media\">\r\n");
      out.write("		<a href=\"https://www.facebook.com\" target=\"_blank\" class=\"social-icon\">\r\n");
      out.write("			<i class=\"fab fa-facebook-f\"></i>\r\n");
      out.write("		</a> <a href=\"https://www.youtube.com\" target=\"_blank\" class=\"social-icon\">\r\n");
      out.write("			<i class=\"fab fa-youtube\"></i>\r\n");
      out.write("		</a> <a href=\"https://www.instagram.com\" target=\"_blank\"\r\n");
      out.write("			class=\"social-icon\"> <i class=\"fab fa-instagram\"></i>\r\n");
      out.write("		</a>\r\n");
      out.write("		<p>&copy; 2024 Online Laundry Management System. All rights\r\n");
      out.write("			reserved.</p>\r\n");
      out.write("	</footer>\r\n");
      out.write("\r\n");
      out.write("	<script>\r\n");
      out.write("        // Validation Function for Tracking Form\r\n");
      out.write("        function validateForm() {\r\n");
      out.write("            const orderNumber = document.getElementById('order-number').value;\r\n");
      out.write("            const errorMessage = document.getElementById('error-message');\r\n");
      out.write("\r\n");
      out.write("            // Check if the order number field is empty\r\n");
      out.write("            if (orderNumber === \"\") {\r\n");
      out.write("                errorMessage.textContent = \"Order number cannot be empty.\";\r\n");
      out.write("                return false;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            // Simple validation: Ensure order number has at least 6 digits\r\n");
      out.write("            const orderNumberPattern = /^[0-9]{6,}$/;\r\n");
      out.write("            if (!orderNumberPattern.test(orderNumber)) {\r\n");
      out.write("                errorMessage.textContent = \"Please enter a valid order number (at least 6 digits).\";\r\n");
      out.write("                return false;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            // Clear error message if input is valid\r\n");
      out.write("            errorMessage.textContent = \"\";\r\n");
      out.write("\r\n");
      out.write("            // Show success alert\r\n");
      out.write("            alert('Your order has been successfully tracked!');\r\n");
      out.write("            \r\n");
      out.write("            // Fetch order status\r\n");
      out.write("            fetchOrderStatus();\r\n");
      out.write("            \r\n");
      out.write("            // Return true to allow form submission\r\n");
      out.write("            return true;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        // Function to simulate fetching order status\r\n");
      out.write("        function fetchOrderStatus() {\r\n");
      out.write("            // You would typically use AJAX or Fetch API to retrieve order status from your server.\r\n");
      out.write("            // This is a placeholder to demonstrate dynamic content update.\r\n");
      out.write("\r\n");
      out.write("            const orderStatusElement = document.getElementById('order-status');\r\n");
      out.write("            orderStatusElement.style.display = 'block';\r\n");
      out.write("            orderStatusElement.innerHTML = `\r\n");
      out.write("                <h2>Order Status</h2>\r\n");
      out.write("                <p>Your order is currently being processed. We will update you with further details soon.</p>\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
