/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.95
 * Generated at: 2024-10-13 12:42:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class services_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Our Services - Online Laundry Management System</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"CSS/services.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css\">\r\n");
      out.write("    <style>\r\n");
      out.write("        /* General styles */\r\n");
      out.write("        body {\r\n");
      out.write("            font-family: 'Arial', sans-serif;\r\n");
      out.write("            background: linear-gradient(to bottom, #ffecd2, #fcb69f); /* Soft gradient background */\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        h1, h2 {\r\n");
      out.write("            color: #ff6f61; /* Bold color for heading */\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        h1 {\r\n");
      out.write("            font-size: 2.5em;\r\n");
      out.write("            margin-bottom: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        p {\r\n");
      out.write("            color: #333;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            font-size: 1.1em;\r\n");
      out.write("            line-height: 1.6em;\r\n");
      out.write("            max-width: 800px;\r\n");
      out.write("            margin: 10px auto 30px auto;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Service Section */\r\n");
      out.write("        .services-section {\r\n");
      out.write("            padding: 40px;\r\n");
      out.write("            background-color: #fff;\r\n");
      out.write("            box-shadow: 0 5px 15px rgba(0, 0, 0, 0.2);\r\n");
      out.write("            border-radius: 12px;\r\n");
      out.write("            max-width: 1200px;\r\n");
      out.write("            margin: 20px auto;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .service-item {\r\n");
      out.write("            margin: 20px auto;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            background-color: #f7f7f7;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            transition: transform 0.3s ease, box-shadow 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .service-item:hover {\r\n");
      out.write("            transform: scale(1.05);\r\n");
      out.write("            box-shadow: 0 8px 25px rgba(0, 0, 0, 0.2);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .service-item h2 {\r\n");
      out.write("            font-size: 1.8em;\r\n");
      out.write("            color: #333;\r\n");
      out.write("            margin-bottom: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .service-item p {\r\n");
      out.write("            color: #666;\r\n");
      out.write("            font-size: 1.2em;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Social Media Footer */\r\n");
      out.write("       /* Social Media Footer */\r\n");
      out.write(".social-media {\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    padding: 20px;\r\n");
      out.write("    background-color: #333; /* Darker background color for the footer */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".social-icon {\r\n");
      out.write("    color: #ff6f61; /* Main color for the social icons */\r\n");
      out.write("    margin: 0 10px;\r\n");
      out.write("    font-size: 1.5em;\r\n");
      out.write("    transition: color 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".social-icon:hover {\r\n");
      out.write("    color: #fff; /* Color change on hover */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        /* Media Queries */\r\n");
      out.write("        @media (max-width: 768px) {\r\n");
      out.write("            h1 {\r\n");
      out.write("                font-size: 2em;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            h2 {\r\n");
      out.write("                font-size: 1.5em;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            p {\r\n");
      out.write("                font-size: 1em;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .service-item {\r\n");
      out.write("                padding: 15px;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <header>\r\n");
      out.write("        <nav>\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><a href=\"home.jsp\">Home</a></li>\r\n");
      out.write("                <li><a href=\"#\">Services</a></li>\r\n");
      out.write("                <li><a href=\"orderinsert.jsp\">Order Pickup</a></li>\r\n");
      out.write("                <li><a href=\"OrderTrackingPage.jsp\">Track Orders</a></li>\r\n");
      out.write("                <li><a href=\"pricing.jsp\">Pricing</a></li>\r\n");
      out.write("                <li><a href=\"contact.jsp\">Contact Us</a></li>\r\n");
      out.write("                <li><a href=\"Login.jsp\">Login</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <div class=\"search-container\">\r\n");
      out.write("                <input type=\"text\" id=\"search\" placeholder=\"Search...\">\r\n");
      out.write("                <button onclick=\"performSearch()\">Search</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </nav>\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("    <!-- Services Section -->\r\n");
      out.write("    <section class=\"services-section\">\r\n");
      out.write("        <h1>Our Services</h1>\r\n");
      out.write("        <p>Discover the range of services we offer to meet your laundry needs.</p>\r\n");
      out.write("        \r\n");
      out.write("        <!-- Service Items -->\r\n");
      out.write("        <div class=\"service-item\">\r\n");
      out.write("            <h2>Express Laundry</h2>\r\n");
      out.write("            <p>Get your laundry done in record time with our express service.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"service-item\">\r\n");
      out.write("            <h2>Eco-Friendly Cleaning</h2>\r\n");
      out.write("            <p>We use environmentally friendly detergents to care for your clothes and the planet.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"service-item\">\r\n");
      out.write("            <h2>Customizable Packages</h2>\r\n");
      out.write("            <p>Create a package that suits your specific laundry requirements.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"service-item\">\r\n");
      out.write("            <h2>Pickup & Delivery</h2>\r\n");
      out.write("            <p>We offer convenient pickup and delivery options to fit your schedule.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <!-- Social Media Footer -->\r\n");
      out.write("    <footer class=\"social-media\">\r\n");
      out.write("        <a href=\"https://www.facebook.com\" target=\"_blank\" class=\"social-icon\">\r\n");
      out.write("            <i class=\"fab fa-facebook-f\"></i>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"https://www.youtube.com\" target=\"_blank\" class=\"social-icon\">\r\n");
      out.write("            <i class=\"fab fa-youtube\"></i>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"https://www.instagram.com\" target=\"_blank\" class=\"social-icon\">\r\n");
      out.write("            <i class=\"fab fa-instagram\"></i>\r\n");
      out.write("        </a>\r\n");
      out.write("    </footer>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"java.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
